### ISSUE TITLE
TypeError on git integration

### ISSUE THREAD

**Issue by ankitpasayat** [vishnuvardhan-kumar/alacrity#3]
Traceback (most recent call last):
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python36-32\Scripts\alacrity-script.py", line 11, in <module>
    load_entry_point('alacrity==1.0.6', 'console_scripts', 'alacrity')()
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\site-packages\alacrity\main.py", line 69, in main
    lib.git_init(package_name, status)
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\site-packages\alacrity\lib.py", line 468, in git_init
    value = subprocess.check_output([git_path, b'init', path])
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "c:\users\ankit\appdata\local\programs\python\python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

**Comment by vishnuvardhan-kumar** [comment]
Fixed with latest commit, Cheers.
